### ISSUE TITLE
Configs do not save after changing them

### ISSUE THREAD

**Issue by telvarost** [calmilamsy/glass-config-api#3]
KydZombie — Today at 11:03 AM
It is technically fully functional, but saving configs is currently bugged. I think it's a single boolean somewhere because it only saves your config changes if you didn't change anything on that open of the config menu
Like say you have config X. If you go to the config to change X and then exit out of the config menu it won't actually change the variable mod-side or in your config file. But if you open the config menu again and don't change X or any other settings, then it will save and everything works

**Comment by calmilamsy** [comment]
Fixed in 1.1.6, forgot to close
